### ISSUE TITLE
Would be great to recalculate on window resize

### ISSUE THREAD

**Issue by seleckis** [saltycrane/use-fit-text#1]
This would be useful if container changes its size when window has been resized

**Comment by saltycrane** [comment]
Hi @seleckis, I published [v1.2.1 to npm](https://www.npmjs.com/package/use-fit-text/v/1.2.1) that allows setting an option to recalculate on window resize. Example usage:

```
const { fontSize, ref } = useFitText({ recalcOnResize: true });
```

Commit: https://github.com/saltycrane/use-fit-text/commit/0bd49d6605e7061c93ab6eb52391b0c62deb3a28
Example: https://github.com/saltycrane/use-fit-text/blob/v1.2.1/examples/pages/index.js#L32-L49

Hope that works for you!

**Comment by seleckis** [comment]
Yes it works, but sometimes it flashes with larger font sizes while window resizing. Chrome/Mac

**Comment by saltycrane** [comment]
Could you try copy/pasting the `useFitText` code into your project and adjusting the `setTimeout` delay here: https://github.com/saltycrane/use-fit-text/blob/master/index.ts#L50 ? Or could you create an example repo the reproduces the problem that I can play with?

**Comment by seleckis** [comment]
I have tried to change setTimeout delay, but still the same issue, it sometimes flashes even with 0 timeout. Check this screen recording: https://we.tl/t-oal2LRcGnY

**Comment by saltycrane** [comment]
@seleckis I published [`use-fit-text@2.0.0`](https://www.npmjs.com/package/use-fit-text/v/2.0.0). See if that works for you.
